export const FETCH_NEWSLETTER_ARCHIVE = 'FETCH_NEWSLETTER_ARCHIVE';
export const FETCH_NEWSLETTER_BY_ID = 'FETCH_NEWSLETTER_BY_ID';

export const SELECT_REQUEST_TYPE = 'SELECT_REQUEST_TYPE';
export const FETCH_SUPPORT_REQUESTS = 'FETCH_SUPPORT_REQUESTS';